version: "3.9"
services:
  api:
    build: ./apps/api
    env_file:
      - ./apps/api/.env.example
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./apps/api/app:/app/app
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mango
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mangomelt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
volumes:
  pgdata:
  minio:
